version: "3.7"
services:
  mcp-clinica:
    image: mcp-clinica-nas-nuvens:latest
    build:
      context: .
      dockerfile: Dockerfile
    
    volumes:
      - mcp_clinica_data:/app/data
    
    networks:
      - minha_rede
    
    environment:
      # Configurações da API da Clínica nas Nuvens
      - CLINICA_NAS_NUVENS_API_URL=${CLINICA_API_URL}
      - CLINICA_NAS_NUVENS_CLIENT_ID=${CLINICA_CLIENT_ID}
      - CLINICA_NAS_NUVENS_CLIENT_SECRET=${CLINICA_CLIENT_SECRET}
      - CLINICA_NAS_NUVENS_CID=${CLINICA_CID}
      
      # Credenciais para SSE e Autenticação
      - CLINICA_AUTHORIZATION=${CLINICA_AUTHORIZATION}
      
      # Configurações do servidor
      - PORT=${SERVER_PORT:-3000}
      - NODE_ENV=${NODE_ENV:-production}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      
      # Configurações do banco de dados
      - DATABASE_ENABLED=${DATABASE_ENABLED:-true}
      - DATABASE_PROVIDER=${DATABASE_PROVIDER:-postgresql}
      - DATABASE_CONNECTION_URI=${DATABASE_CONNECTION_URI}
      
      # Configurações de webhook
      - WEBHOOK_ENABLED=${WEBHOOK_ENABLED:-false}
      - WEBHOOK_URL=${WEBHOOK_URL}
      
      # Integração com RabbitMQ (se necessário)
      - RABBITMQ_ENABLED=${RABBITMQ_ENABLED:-false}
      - RABBITMQ_URI=${RABBITMQ_URI}
    
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
        - node.role == manager
      labels:
      - traefik.enable=1
      - traefik.http.routers.mcp-clinica.rule=Host(`clinica.consultoriodeouro.com.br`)
      - traefik.http.routers.mcp-clinica.entrypoints=websecure
      - traefik.http.routers.mcp-clinica.priority=1
      - traefik.http.routers.mcp-clinica.tls.certresolver=letsencryptresolver
      - traefik.http.routers.mcp-clinica.service=mcp-clinica
      - traefik.http.services.mcp-clinica.loadbalancer.server.port=3000
      - traefik.http.services.mcp-clinica.loadbalancer.passHostHeader=true

volumes:
  mcp_clinica_data:
    external: true
    name: mcp_clinica_data

networks:
  minha_rede:
    external: true
    name: minha_rede
